# Generated by Django 5.1.7 on 2025-03-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='acuerdo_firmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='caja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='cargador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='case',
            field=models.BooleanField(default=False),
        ),
    ]
