# Generated by Django 5.1.7 on 2025-03-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_asignacion_acuerdo_firmado_asignacion_caja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='id_economico',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
